version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./utl/migration/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: always
    networks:
      - default

  web:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge